-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'SESSION_EXPIRING_SOON';
ALTER TYPE "NotificationType" ADD VALUE 'CHECKOUT';
ALTER TYPE "NotificationType" ADD VALUE 'KICKED_FROM_SESSION';
ALTER TYPE "NotificationType" ADD VALUE 'LEADERSHIP_TRANSFERRED';
